-- MySQL Script generated by MySQL Workbench
-- Sat Nov 29 12:17:11 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema progetto_genere
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `immatricolati_laurea`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `immatricolati_laurea` ;

CREATE TABLE IF NOT EXISTS `immatricolati_laurea` (
  `id_immatricolati` INT NOT NULL AUTO_INCREMENT,
  `ANNO` VARCHAR(15) NULL DEFAULT NULL,
  `AteneoNOME` TEXT NULL DEFAULT NULL,
  `AteneoREGIONE` VARCHAR(30) NULL DEFAULT NULL,
  `CorsoTIPO` TEXT NULL DEFAULT NULL,
  `DESC_FoET2013` TEXT NULL DEFAULT NULL,
  `Genere` VARCHAR(3) NULL DEFAULT NULL,
  PRIMARY KEY (`id_immatricolati`))
ENGINE = InnoDB
AUTO_INCREMENT = 14991
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
